const API_URL = "https://nexus-backend-service.onrender.com";; // FastAPI address

// Handle file selection display
document.getElementById('file-upload').addEventListener('change', function (e) {
    const fileList = document.getElementById('file-list');
    fileList.innerHTML = Array.from(e.target.files).map(f => `<div>📄 ${f.name}</div>`).join('');
});

async function syncData() {
    const files = document.getElementById('file-upload').files;
    const model = document.getElementById('model-select').value;
    const statusDiv = document.getElementById('sync-status');
    const syncBtn = document.getElementById('sync-btn');

    if (files.length === 0) {
        statusDiv.innerHTML = "⚠️ Select files first.";
        return;
    }

    const formData = new FormData();
    for (let i = 0; i < files.length; i++) {
        formData.append("files", files[i]);
    }
    formData.append("model", model);

    syncBtn.disabled = true;
    syncBtn.innerText = "Syncing...";
    statusDiv.innerHTML = "";

    try {
        const response = await fetch(`${API_URL}/upload`, {
            method: 'POST',
            body: formData
        });
        const result = await response.json();

        if (response.ok) {
            statusDiv.innerHTML = `✅ ${result.message}`;
        } else {
            statusDiv.innerHTML = `❌ Error: ${result.detail}`;
        }
    } catch (error) {
        statusDiv.innerHTML = "❌ Failed to connect to server.";
    } finally {
        syncBtn.disabled = false;
        syncBtn.innerText = "Sync Data to AI";
    }
}

function handleKeyPress(e) {
    if (e.key === 'Enter') {
        sendMessage();
    }
}

function appendMessage(role, text) {
    const container = document.getElementById('chat-container');
    const msgDiv = document.createElement('div');
    msgDiv.className = `message ${role}`;

    let htmlContent = text;
    let chartConfigs = [];

    // 1. Intercept Chart Blocks generated by the AI
    const chartRegex = /```chart\n([\s\S]*?)\n```/g;
    htmlContent = htmlContent.replace(chartRegex, (match, jsonString) => {
        // Create a unique ID for this specific chart
        const chartId = 'chart-' + Math.random().toString(36).substr(2, 9);
        try {
            const config = JSON.parse(jsonString);
            chartConfigs.push({ id: chartId, config: config });
            // Inject a canvas element into the HTML where the text used to be
            return `<div class="chart-container"><canvas id="${chartId}"></canvas></div>`;
        } catch (e) {
            return `<div class="error-msg">⚠️ AI generated invalid chart data.</div>`;
        }
    });

    // 2. Parse Markdown (Transforms raw tables, lists, and bold text into beautiful HTML)
    htmlContent = marked.parse(htmlContent);

    msgDiv.innerHTML = `<div class="bubble">${htmlContent}</div>`;
    container.appendChild(msgDiv);

    // 3. Render the interactive charts AFTER the canvas is injected into the screen
    chartConfigs.forEach(chart => {
        const ctx = document.getElementById(chart.id).getContext('2d');
        new Chart(ctx, chart.config);
    });

    container.scrollTop = container.scrollHeight;
}

async function sendMessage() {
    const input = document.getElementById('user-input');
    const message = input.value.trim();
    const model = document.getElementById('model-select').value;
    const sendBtn = document.getElementById('send-btn');

    if (!message) return;

    appendMessage('user', message);
    input.value = '';
    sendBtn.disabled = true;

    // Add a loading message
    const container = document.getElementById('chat-container');
    const loadingDiv = document.createElement('div');
    loadingDiv.className = `message ai loading`;
    loadingDiv.innerHTML = `<div class="bubble">Thinking...</div>`;
    container.appendChild(loadingDiv);
    container.scrollTop = container.scrollHeight;

    const formData = new FormData();
    formData.append("message", message);
    formData.append("model", model);

    try {
        const response = await fetch(`${API_URL}/chat`, {
            method: 'POST',
            body: formData
        });
        const result = await response.json();

        container.removeChild(loadingDiv); // Remove loading

        if (response.ok) {
            appendMessage('ai', result.answer);
        } else {
            appendMessage('ai', `⚠️ Error: ${result.detail}`);
        }
    } catch (error) {
        container.removeChild(loadingDiv);
        appendMessage('ai', "❌ Failed to connect to backend server. Is FastAPI running?");
    } finally {
        sendBtn.disabled = false;
    }
}